"use strict";
exports.__esModule = true;
var file1_1 = require("./file1");
console.log(file1_1.greeting);
file1_1.greet();
var prod = new file1_1.Product('Laptop', 45000);
prod.getinfo();
var trial = require("./file1");
console.log(trial.greeting);
trial.greet();
var prod = new trial.Product('Laptop', 42000);
prod.getinfo();
